const initialKeyboard = ['<div class="upper-part key-value">°</div> <div class="lower-part key-value">§ </div>',
 '<div class="upper-part key-value">+         </div> <div class="lower-part key-value">1      </div>',
 '<div class="upper-part key-value">"    </div> <div class="lower-part key-value">2      </div>',
 '<div class="upper-part key-value">*     </div> <div class="lower-part key-value">3      </div>',
 '<div class="upper-part key-value">ç         </div> <div class="lower-part key-value">4      </div>',
 '<div class="upper-part key-value">%  </div> <div class="lower-part key-value">5      </div>',
 '<div class="upper-part key-value">&amp;     </div> <div class="lower-part key-value">6      </div>',
 '<div class="upper-part key-value">/     </div> <div class="lower-part key-value">7      </div>',
 '<div class="upper-part key-value">(    </div> <div class="lower-part key-value">8     </div>',
 '<div class="upper-part key-value">)    </div> <div class="lower-part key-value">9      </div>',
 '<div class="upper-part key-value">=         </div> <div class="lower-part key-value">0       </div>',
 '<div class="upper-part key-value">?   </div> <div class="lower-part key-value">\' </div>',
 '<div class="upper-part key-value">`   </div> <div class="lower-part key-value">^  </div>',
 '<div class="qType"> <div class="ko2 key-value">ㅃ  …e">Q       </div> <div class="ko2">ㅂ</div> </div>',
 '<div class="qType"> <div class="ko2 key-value">ㅉ  …e">W       </div> <div class="ko2">ㅈ</div> </div>',
 '<div class="qType"> <div class="ko2 key-value">ㄸ  …e">E       </div> <div class="ko2">ㄷ</div> </div>',
 '<div class="qType"> <div class="ko2 key-value">ㄲ  …e">R       </div> <div class="ko2">ㄱ</div> </div>',
 '<div class="qType"> <div class="ko2 key-value">ㅆ  …e">T       </div> <div class="ko2">ㅅ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">Z  … <div class="ko1 key-value">ㅛ       </div> </div>',
 '<div class="aType"> <div class="de1 key-value">U  … <div class="ko1 vowel key-value">ㅕ </div> </div>',
 '<div class="aType"> <div class="de1 key-value">I  … <div class="ko1 vowel key-value">ㅑ </div> </div>',
 '<div class="qType"> <div class="ko2 key-value">ㅒ  …e">O       </div> <div class="ko2">ㅐ</div> </div>',
 '<div class="qType"> <div class="ko2 key-value">ㅖ  …e">P       </div> <div class="ko2">ㅔ</div> </div>',
 'é &nbsp;&nbsp; ö',
 '<div class="upper-part key-value">!</div> <div class="lower-part key-value">"</div>',
 '<div class="upper-part key-value">£</div> <div class="lower-part key-value">$</div>',
 '<div class="aType"> <div class="de1 key-value">A</div> <div class="ko1 key-value">ㅁ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">S</div> <div class="ko1 key-value">ㄴ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">D</div> <div class="ko1 key-value">ㅇ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">F</div> <div class="ko1 key-value">ㄹ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">G</div> <div class="ko1 key-value">ㅎ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">H</div> <div class="ko1 key-value">ㅗ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">J</…> <div class="ko1 vowel key-value">ㅓ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">K</…> <div class="ko1 vowel key-value">ㅏ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">L</…> <div class="ko1 vowel key-value">ㅣ</div> </div>',
 '<div class="key-value">é &nbsp;&nbsp; ö</div>',
 '<div class="key-value">à &nbsp;&nbsp; ä</div>',
 '&lt;',
 '<div class="aType"> <div class="de1 key-value">Y</div> <div class="ko1 key-value">ㅋ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">X</div> <div class="ko1 key-value">ㅌ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">C</div> <div class="ko1 key-value">ㅊ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">V</div> <div class="ko1 key-value">ㅍ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">B</div> <div class="ko1 key-value">ㅠ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">N</div> <div class="ko1 key-value">ㅜ</div> </div>',
 '<div class="aType"> <div class="de1 key-value">M</div> <div class="ko1 key-value">ㅡ</div> </div>',
 '<div class="upper-part key-value">;</div> <div class="lower-part key-value">,</div>',
 '<div class="upper-part key-value">:</div> <div class="lower-part key-value">.</div>',
 '<div class="upper-partkey-value">―</div> <div class="lower-part key-value">-</div>'];
